version: "3.8"
services:
  postgres:
    container_name: postgres
    image: postgres:16.2
    environment:
      POSTGRES_USER: lotteryusr
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: lottery
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: